//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehículos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidoCliente
    {
        public int Id { get; set; }
        public int IdPedido { get; set; }
        public int CodigoVehiculo { get; set; }
        public int Cantidad { get; set; }
        public int PrecioUnitario { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual PedidoCliente PedidoCliente { get; set; }
    }
}
