//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehículos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBVentaVehiculosEntities : DbContext
    {
        public DBVentaVehiculosEntities()
            : base("name=DBVentaVehiculosEntities")
        {
        }
  //Si me suben los cambios

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<CitaTaller> CitaTallers { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Concesionario> Concesionarios { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<DetalleDevolucion> DetalleDevolucions { get; set; }
        public virtual DbSet<DetalleFacturaVenta> DetalleFacturaVentas { get; set; }
        public virtual DbSet<DetallePedidoCliente> DetallePedidoClientes { get; set; }
        public virtual DbSet<DevolucionVenta> DevolucionVentas { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<EmpleadoCargo> EmpleadoCargoes { get; set; }
        public virtual DbSet<FacturaVenta> FacturaVentas { get; set; }
        public virtual DbSet<FotosEmpleado> FotosEmpleados { get; set; }
        public virtual DbSet<Garantia> Garantias { get; set; }
        public virtual DbSet<ImagenesVehiculo> ImagenesVehiculoes { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Modelo> Modeloes { get; set; }
        public virtual DbSet<NotaCredito> NotaCreditoes { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<PedidoCliente> PedidoClientes { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<ReclamoGarantia> ReclamoGarantias { get; set; }
        public virtual DbSet<ServicioTaller> ServicioTallers { get; set; }
        public virtual DbSet<Sucursal> Sucursals { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Unidad> Unidads { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Usuario_Perfil> Usuario_Perfil { get; set; }
        public virtual DbSet<Vehiculo> Vehiculoes { get; set; }
    }
}
