//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehículos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReclamoGarantia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReclamoGarantia()
        {
            this.CitaTallers = new HashSet<CitaTaller>();
            this.DevolucionVentas = new HashSet<DevolucionVenta>();
        }
    
        public int Id { get; set; }
        public int IdGarantia { get; set; }
        public System.DateTime FechaReclamo { get; set; }
        public string DescripcionProblema { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public string SolucionAplicada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitaTaller> CitaTallers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionVenta> DevolucionVentas { get; set; }
        public virtual Garantia Garantia { get; set; }
    }
}
